syntax = "proto3";

package traceability;

option java_package = "com.example.assignment.grpc";
option java_multiple_files = true;

service TraceabilityService {

  rpc GetAnimalsByProduct (ProductRequest) returns (AnimalsResponse);

  rpc GetProductsByAnimal (AnimalRequest) returns (ProductsResponse);
}

message ProductRequest {
  int64 product_id = 1;
}

message AnimalsResponse {
  repeated int64 registration_numbers = 1;
}

message AnimalRequest {
  int64 animal_id = 1;
}

message ProductsResponse {
  repeated ProductSummary products = 1;
}

message ProductSummary {
  int64 id = 1;
  bool half = 2;
}