spring.application.name=Pro 3 - Assignment II
spring.sql.init.mode=always

spring.datasource.url=jdbc:postgresql://localhost:5432/assignment_ii
spring.datasource.username=postgres
spring.datasource.password=viavia

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
